db:
  tables:
    spells:
      - {name: id, type: INT PRIMARY KEY UNIQUE NOT NULL}
      - {name: index, type: TEXT NOT NULL}
      - {name: desc, type: TEXT NOT NULL}
      - {name: higher_level, type: TEXT NOT NULL}
      - {name: range, type: TEXT NOT NULL}
      - {name: material, type: TEXT NOT NULL}
      - {name: ritual, type: TEXT NOT NULL}
      - {name: duration, type: TEXT NOT NULL}
      - {name: concentration, type: TEXT NOT NULL}
      - {name: casting_time, type: TEXT NOT NULL}
      - {name: level, type: TEXT NOT NULL}
      - {name: attack_type, type: TEXT NOT NULL}
      - {name: damage, type: }
      - {name: components, type: }
      - {name: level, type: TEXT NOT NULL}
      - {name: level, type: TEXT NOT NULL}
      - {name: level, type: TEXT NOT NULL}
      - {name: level, type: TEXT NOT NULL}
      - {name: level, type: TEXT NOT NULL}
    components:
      - {name: id, type: INT PRIMARY KEY UNIQUE NOT NULL}
      - {name: litera, type: TEXT NOT NULL}
    damage:
      - {name: id, type: INT PRIMARY KEY UNIQUE NOT NULL}
      - {name: damage_type, type: TEXT NOT NULL}
      - {name: damage_type_url, type: TEXT NOT NULL}


CREATE TABLE damage_types (
  damage_type_id serial PRIMARY KEY UNIQUE NOT NULL,
  damage_type TEXT NOT NULL,
  damage_type_url TEXT NOT NULL
);

CREATE TABLE components (
  component_id serial PRIMARY KEY UNIQUE NOT NULL,
  litera TEXT NOT NULL
);

CREATE TABLE school (
  school_id serial PRIMARY KEY UNIQUE NOT NULL,
  school_name TEXT NOT NULL,
  school_url TEXT NOT NULL
);

CREATE TABLE classes (
  class_id serial PRIMARY KEY UNIQUE NOT NULL,
  class_name TEXT NOT NULL,
  class_url TEXT NOT NULL
);

CREATE TABLE subclasses (
  subclass_id serial PRIMARY KEY UNIQUE NOT NULL,
  subclass_name TEXT NOT NULL,
  subclass_url TEXT NOT NULL
);



CREATE TABLE spells (
  spell_id serial PRIMARY KEY UNIQUE NOT NULL,
  spell_name TEXT UNIQUE NOT NULL,
  spell_damage_type INT DEFAULT NULL,
  spell_url TEXT NOT NULL,

  FOREIGN KEY (spell_damage_type) REFERENCES damage_types (damage_type_id)
);


INSERT INTO components(litera) VALUES ('S');
INSERT INTO components(litera) VALUES ('M');
INSERT INTO components(litera) VALUES ('V');

INSERT INTO classes(class_name, class_url) VALUES ('Wizard', '/api/classes/wizard');
INSERT INTO classes(class_name, class_url) VALUES ('Druid', '/api/classes/druid');

INSERT INTO damage_types(damage_type, damage_typeurl) VALUES ('Acid', '/api/damage-types/acid');
INSERT INTO damage_types(damage_type, damage_typeurl) VALUES ('Acid', '/api/damage-types/acid');